# Pair Programming NumPy IV

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [1]:
import numpy as np

In [2]:
np.random.seed(29)

In [3]:
array1 = np.random.random_sample((4,5))
array1

array([[0.86375999, 0.28490597, 0.07325639, 0.7632372 , 0.45271906],
       [0.54229687, 0.72663578, 0.84890511, 0.76819998, 0.73314372],
       [0.24198642, 0.72030869, 0.05837731, 0.40966893, 0.61067227],
       [0.25591487, 0.28567193, 0.68446375, 0.84091974, 0.80915342]])

In [5]:
np.random.seed(29)
array2 = np.random.random_sample((4,5))

In [6]:
array2

array([[0.86375999, 0.28490597, 0.07325639, 0.7632372 , 0.45271906],
       [0.54229687, 0.72663578, 0.84890511, 0.76819998, 0.73314372],
       [0.24198642, 0.72030869, 0.05837731, 0.40966893, 0.61067227],
       [0.25591487, 0.28567193, 0.68446375, 0.84091974, 0.80915342]])

2. Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.


In [7]:
array3 = np.random.uniform(0,10, size = (2,3,5))
array3

array([[[6.34957546e-04, 9.23610095e+00, 8.06965163e+00, 9.56012401e+00,
         4.84728990e+00],
        [6.62574004e+00, 7.33806658e+00, 4.66112127e+00, 8.05448199e+00,
         4.37987529e+00],
        [1.29039770e+00, 6.42150572e+00, 4.78643703e+00, 6.58120772e+00,
         8.33529313e-01]],

       [[6.63723138e+00, 4.90940085e+00, 7.55314542e+00, 4.27873001e+00,
         3.29810602e+00],
        [4.77700018e+00, 9.19536873e+00, 3.07537439e+00, 9.84919299e+00,
         1.13741203e+00],
        [9.70515185e+00, 8.73361662e+00, 9.47262038e+00, 2.36569680e+00,
         8.57536015e+00]]])

In [8]:
array3_unicos = np.unique(array3)
array3_unicos

array([6.34957546e-04, 8.33529313e-01, 1.13741203e+00, 1.29039770e+00,
       2.36569680e+00, 3.07537439e+00, 3.29810602e+00, 4.27873001e+00,
       4.37987529e+00, 4.66112127e+00, 4.77700018e+00, 4.78643703e+00,
       4.84728990e+00, 4.90940085e+00, 6.42150572e+00, 6.58120772e+00,
       6.62574004e+00, 6.63723138e+00, 7.33806658e+00, 7.55314542e+00,
       8.05448199e+00, 8.06965163e+00, 8.57536015e+00, 8.73361662e+00,
       9.19536873e+00, 9.23610095e+00, 9.47262038e+00, 9.56012401e+00,
       9.70515185e+00, 9.84919299e+00])

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [10]:
array4 = np.random.binomial(10,0.3, size = (2,3,5))
array4

array([[[3, 3, 4, 2, 5],
        [3, 2, 6, 3, 1],
        [5, 4, 4, 1, 2]],

       [[2, 4, 2, 1, 4],
        [8, 4, 4, 3, 3],
        [4, 3, 3, 5, 3]]])

In [11]:
array4_unicos = np.unique(array4)
array4_unicos

array([1, 2, 3, 4, 5, 6, 8])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
- Elementos comunes entre los dos arrays
- Unión de los dos arrays
- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [12]:
# elementos comunes

np.intersect1d(array3_unicos, array4_unicos)

# devuelve un array vacio porque no hay ningun elemento en comun (array3 era todo floats y array4 era solo integers)

array([], dtype=float64)

In [13]:
# union de los dos arrays

np.union1d(array3_unicos, array4_unicos)

# devuelve todos los valores de los dos arrays (porque no tienen elementos en comun); los integers ahora aparecen como floats 
# porque los arrays solo pueden tener un solo tipo de datos

array([6.34957546e-04, 8.33529313e-01, 1.00000000e+00, 1.13741203e+00,
       1.29039770e+00, 2.00000000e+00, 2.36569680e+00, 3.00000000e+00,
       3.07537439e+00, 3.29810602e+00, 4.00000000e+00, 4.27873001e+00,
       4.37987529e+00, 4.66112127e+00, 4.77700018e+00, 4.78643703e+00,
       4.84728990e+00, 4.90940085e+00, 5.00000000e+00, 6.00000000e+00,
       6.42150572e+00, 6.58120772e+00, 6.62574004e+00, 6.63723138e+00,
       7.33806658e+00, 7.55314542e+00, 8.00000000e+00, 8.05448199e+00,
       8.06965163e+00, 8.57536015e+00, 8.73361662e+00, 9.19536873e+00,
       9.23610095e+00, 9.47262038e+00, 9.56012401e+00, 9.70515185e+00,
       9.84919299e+00])

In [14]:
# que elementos estan en array3_unicos y no en array4_unicos

np.setdiff1d(array3_unicos, array4_unicos)

# devuelve todos los elementos de array3_unicos porque no tienen elementos en comun

array([6.34957546e-04, 8.33529313e-01, 1.13741203e+00, 1.29039770e+00,
       2.36569680e+00, 3.07537439e+00, 3.29810602e+00, 4.27873001e+00,
       4.37987529e+00, 4.66112127e+00, 4.77700018e+00, 4.78643703e+00,
       4.84728990e+00, 4.90940085e+00, 6.42150572e+00, 6.58120772e+00,
       6.62574004e+00, 6.63723138e+00, 7.33806658e+00, 7.55314542e+00,
       8.05448199e+00, 8.06965163e+00, 8.57536015e+00, 8.73361662e+00,
       9.19536873e+00, 9.23610095e+00, 9.47262038e+00, 9.56012401e+00,
       9.70515185e+00, 9.84919299e+00])

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.


In [32]:
array_1 = np.random.randint(1,100, (2,4,10))
array_1

array([[[58, 26,  9, 91, 36, 43, 54, 97, 98, 75],
        [27, 22, 84, 45, 91, 39, 29,  1,  2, 41],
        [32, 52, 24, 19, 44, 79, 17, 50, 75, 99],
        [23, 21, 57, 60, 11, 90, 75, 60, 11,  6]],

       [[40, 97, 80, 77,  7, 25, 22, 53, 24, 50],
        [48, 86, 10, 26, 56, 28, 31, 97, 33, 19],
        [51, 40, 13, 40, 73, 54, 57, 80, 46,  2],
        [73, 41, 27, 63, 33, 18, 33,  6, 95, 29]]])

In [33]:
array_2 = np.random.randint(1,100, (2,4,10))
array_2

array([[[34, 24, 93, 24, 88, 56, 88, 44, 16, 29],
        [ 6, 65, 89, 28, 35, 16, 19, 83, 67, 99],
        [46, 16, 65, 42, 59, 83, 21, 89, 35, 83],
        [ 7, 28,  4, 18, 98, 55, 99, 25, 16, 96]],

       [[29, 78, 34, 61, 40, 81, 24, 25, 92, 91],
        [38, 30, 43, 22,  4,  1,  9, 22, 81, 37],
        [60,  4, 16, 18, 26, 92, 71, 56, 38, 25],
        [52,  3, 39, 32, 22, 59, 55, 87, 61, 13]]])

- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [34]:
array_1 = np.unique(array_1)
array_1

array([ 1,  2,  6,  7,  9, 10, 11, 13, 17, 18, 19, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 31, 32, 33, 36, 39, 40, 41, 43, 44, 45, 46, 48, 50, 51,
       52, 53, 54, 56, 57, 58, 60, 63, 73, 75, 77, 79, 80, 84, 86, 90, 91,
       95, 97, 98, 99])

In [35]:
array_2 = np.unique(array_2)
array_2

array([ 1,  3,  4,  6,  7,  9, 13, 16, 18, 19, 21, 22, 24, 25, 26, 28, 29,
       30, 32, 34, 35, 37, 38, 39, 40, 42, 43, 44, 46, 52, 55, 56, 59, 60,
       61, 65, 67, 71, 78, 81, 83, 87, 88, 89, 91, 92, 93, 96, 98, 99])

- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [36]:
array_3 = np.setdiff1d(array_1,array_2)
array_3

array([ 2, 10, 11, 17, 23, 27, 31, 33, 36, 41, 45, 48, 50, 51, 53, 54, 57,
       58, 63, 73, 75, 77, 79, 80, 84, 86, 90, 95, 97])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [37]:
array_4 = np.setdiff1d(array_2,array_1)
array_4

array([ 3,  4, 16, 30, 34, 35, 37, 38, 42, 55, 59, 61, 65, 67, 71, 78, 81,
       83, 87, 88, 89, 92, 93, 96])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [38]:
array_5 = np.intersect1d(array_1, array_2)
array_5

array([ 1,  6,  7,  9, 13, 18, 19, 21, 22, 24, 25, 26, 28, 29, 32, 39, 40,
       43, 44, 46, 52, 56, 60, 91, 98, 99])

- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [39]:
print(len(array_1)) # valores unicos de array_1 original
print(len(array_2)) # valores unicos de array_2 original
print(len(array_3)) # la diferencia entre array_1 y array_2 (setdiff)
print(len(array_4)) # la diferencia entre array_2 y array_1 (setdiff)
print(len(array_5)) # los elementos en comun entre array_1 y array_2 (intersect)


55
50
29
24
26


In [44]:
(len(array_1) - len(array_2) + len(array_5)) == (len(array_3) - len(array_4) + len(array_5))

True

In [ ]:
# esta ecuacion es True porque la diferencia de la congitud entre array_1 y array_2 es la misma que la diferencia 
# de la longitud entre array_3 y array_4. 