# Pair Programming NumPy III

In [1]:
import numpy as np

En esta lección hemos aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.  
1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales.

In [2]:
array1 = np.random.rand(2,3,5).round(1)
array1

array([[[0.8, 0.8, 0.7, 0.5, 0.2],
        [0.4, 0.7, 0.6, 0.3, 0.4],
        [0.2, 0. , 0.8, 0.2, 0.1]],

       [[0.2, 0.4, 0.6, 0.4, 0.1],
        [0.7, 0.7, 0.5, 0.7, 0.5],
        [0.5, 0.7, 0.7, 0.4, 0.7]]])

2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal. 

In [3]:
media = np.mean(array1).round(1)
media

0.5

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
maximo = np.max(array1).round(1)
maximo

0.8

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.


In [5]:
minimo = np.min(array1).round(1)
minimo

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.  

    Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:  
    - Si el valor del array es igual que la media, se reemplaza por "A".
    - Si el valor del array es mayor que la media, se reemplaza por "B".
    - Si el valor del array es menor que la media, se reemplaza por "C".
    - Si el valor es igual que el máximo, se reemplaza por "D".
    - Si el valor es igual que el mínimo, se reemplaza por "E".
    ```python
    # a modo de ejemplo. Si tenemos el siguiente array
    [[[0.4, 0.7, 0.2, 0.9, 0.2],
        [0.1, 0.9, 0.6, 0.1, 0.2],
        [1. , 0.2, 0.1, 0.8, 0.3]],

    [[0. , 0.3, 0.4, 0.5, 0.1],
        [0.5, 0.7, 0.9, 0. , 0.8],
        [0.5, 0.3, 0.5, 0.8, 0.1]]])

    # sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

    # nuestro array vacío debería quedar como este: 
    [[["A", "B", "C", "B", "C"],
        ["C", "B", "B", "C", "C"],
        ["D" , "C", "C", "B", "C"]],

    [["E" , "C", "A", "B", "C"],
        ["B", "B","B", "E" , "B"],
        ["B", "C", "B", "B", "C"]]])
    ```
    💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales. 

In [6]:
vacio = np.empty((2,3,5), dtype=str)
vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [7]:
for indice_mat, matriz in enumerate(array1):
    for indice_fila, fila in enumerate(matriz):
        for indice_col, columna in enumerate(fila):
            if array1[indice_mat,indice_fila, indice_col] == np.mean(array1).round(1):
                vacio[indice_mat,indice_fila, indice_col] = 'A'
            elif array1[indice_mat,indice_fila, indice_col] > np.mean(array1):
                vacio[indice_mat,indice_fila, indice_col] = 'B'
            elif array1[indice_mat,indice_fila, indice_col] < np.mean(array1):
                vacio[indice_mat,indice_fila, indice_col] = 'C'
            if array1[indice_mat,indice_fila, indice_col] == np.max(array1):
                vacio[indice_mat,indice_fila, indice_col] = 'D'
            elif array1[indice_mat,indice_fila, indice_col] == np.min(array1):
                vacio[indice_mat,indice_fila, indice_col] = 'E'
vacio

array([[['D', 'D', 'B', 'A', 'C'],
        ['C', 'B', 'B', 'C', 'C'],
        ['C', 'E', 'D', 'C', 'C']],

       [['C', 'C', 'B', 'C', 'C'],
        ['B', 'B', 'A', 'B', 'A'],
        ['A', 'B', 'B', 'C', 'B']]], dtype='<U1')

In [8]:
# otra posible solución:
vacio2 = np.empty((2,3,5), dtype=str)
vacio2.shape

(2, 3, 5)

In [9]:
for indice_mat in range(vacio2.shape[0]):
    for indice_fila in range(vacio2.shape[1]):
        for indice_col in range(vacio2.shape[2]):
            if array1[indice_mat,indice_fila, indice_col] == np.mean(array1).round(1):
                vacio2[indice_mat,indice_fila, indice_col] = 'A'
            elif array1[indice_mat,indice_fila, indice_col] > np.mean(array1):
                vacio2[indice_mat,indice_fila, indice_col] = 'B'
            elif array1[indice_mat,indice_fila, indice_col] < np.mean(array1):
                vacio2[indice_mat,indice_fila, indice_col] = 'C'
            if array1[indice_mat,indice_fila, indice_col] == np.max(array1):
                vacio2[indice_mat,indice_fila, indice_col] = 'D'
            elif array1[indice_mat,indice_fila, indice_col] == np.min(array1):
                vacio2[indice_mat,indice_fila, indice_col] = 'E'
vacio2

array([[['D', 'D', 'B', 'A', 'C'],
        ['C', 'B', 'B', 'C', 'C'],
        ['C', 'E', 'D', 'C', 'C']],

       [['C', 'C', 'B', 'C', 'C'],
        ['B', 'B', 'A', 'B', 'A'],
        ['A', 'B', 'B', 'C', 'B']]], dtype='<U1')

6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.  

    En este caso:
    - Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
    - Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
    - Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.  
    
    Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [23]:
# solcución cambiando la forma al principio y no al final
array2 = np.empty(30, dtype=int)
array2

array([           30873408,                   0, 7597414380956903779,
       8386387640092685422, 8511917019643144545, 7955925896722213985,
       7953763900378870794, 8083217375687632231, 6944653332839410793,
       7935410980476553786, 7953766387382562416, 3251647507869673522,
       3328260318368181809, 6992446851629719596, 3539929536506458738,
       3690199853871609134, 3978136634597059635, 2980594823435204400,
       3346295607898553866, 2896498875196207713, 3183534901335830619,
                        81,     139714846756000,     139714846756000,
       8241879965841649257, 2318844026221584754, 3179576659273588768,
       4122255134160728864, 3976168435753498162, 6716610011817260344])

In [24]:
array2_3d = array2.reshape(2,3,5)
array2_3d

array([[[           30873408,                   0, 7597414380956903779,
         8386387640092685422, 8511917019643144545],
        [7955925896722213985, 7953763900378870794, 8083217375687632231,
         6944653332839410793, 7935410980476553786],
        [7953766387382562416, 3251647507869673522, 3328260318368181809,
         6992446851629719596, 3539929536506458738]],

       [[3690199853871609134, 3978136634597059635, 2980594823435204400,
         3346295607898553866, 2896498875196207713],
        [3183534901335830619,                  81,     139714846756000,
             139714846756000, 8241879965841649257],
        [2318844026221584754, 3179576659273588768, 4122255134160728864,
         3976168435753498162, 6716610011817260344]]])

In [25]:
for indice_mat, matriz in enumerate(array2_3d):
    for indice_fila, fila in enumerate(matriz):
        for indice_col, columna in enumerate(fila):
            if vacio[indice_mat, indice_fila, indice_col] == 'A' or vacio[indice_mat, indice_fila, indice_col] == 'B':
                array2_3d[indice_mat, indice_fila, indice_col] = 1
            elif vacio[indice_mat,indice_fila, indice_col] == 'C' or vacio[indice_mat, indice_fila, indice_col] == 'D':
                array2_3d[indice_mat, indice_fila, indice_col] = 2
            elif vacio[indice_mat,indice_fila, indice_col] == 'E':
                array2_3d[indice_mat, indice_fila, indice_col] = 3
array2_3d

array([[[2, 2, 1, 1, 2],
        [2, 1, 1, 2, 2],
        [2, 3, 2, 2, 2]],

       [[2, 2, 1, 2, 2],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 2, 1]]])

In [13]:
# cambiando la forma al final
array3 = np.empty(30, dtype=int)
array3

array([4605380978949069210, 4605380978949069210, 4604480259023595110,
       4602678819172646912, 4596373779694328218, 4600877379321698714,
       4604480259023595110, 4603579539098121011, 4599075939470750515,
       4600877379321698714, 4596373779694328218,                   0,
       4605380978949069210, 4596373779694328218, 4591870180066957722,
       4596373779694328218, 4600877379321698714, 4603579539098121011,
       4600877379321698714, 4591870180066957722, 4604480259023595110,
       4604480259023595110, 4602678819172646912, 4604480259023595110,
       4602678819172646912, 4602678819172646912, 4604480259023595110,
       4604480259023595110, 4600877379321698714, 4604480259023595110])

In [14]:
vacio

array([[['D', 'D', 'B', 'A', 'C'],
        ['C', 'B', 'B', 'C', 'C'],
        ['C', 'E', 'D', 'C', 'C']],

       [['C', 'C', 'B', 'C', 'C'],
        ['B', 'B', 'A', 'B', 'A'],
        ['A', 'B', 'B', 'C', 'B']]], dtype='<U1')

In [20]:
contador = 0
for matriz in vacio:
    for fila in matriz:
        for elemento in fila:
            if elemento == 'A' or elemento == 'B':
                array3[contador] = 1
            elif elemento == 'C' or elemento == 'D':
                array3[contador] = 2
            else:
                array3[contador] = 3
            contador += 1

In [21]:
array3

array([2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 3, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1])

In [22]:
array3_3d = array3.reshape(2,3,5)
array3_3d

array([[[2, 2, 1, 1, 2],
        [2, 1, 1, 2, 2],
        [2, 3, 2, 2, 2]],

       [[2, 2, 1, 2, 2],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 2, 1]]])