# Pair Programming NumPy II

1. Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
- El valor de la primera fila y la segunda columna.

In [1]:
import numpy as np

In [2]:
array_2d = np.arange(15).reshape(5,3)
array_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [3]:
array_2d[0,1]

1

- Los valores de la segunda fila y las dos primeras columnas.

In [4]:
array_2d[1,0:2]

array([3, 4])

- Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [5]:
array_2d[::2,:]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

- Extraed los valores que sean mayores que 0.5.

In [6]:
array_2d[array_2d > 0.5]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [7]:
array_2d[(array_2d < 0.2) | (array_2d > 0.5)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

2. Cread dos array de tres dimensiones:
- El primero de 2 matrices, 5 filas y 3 columnas.

In [8]:
array_3d1 = np.random.randint(1,30, (2,5,3))
array_3d1

array([[[21, 15,  4],
        [ 2, 26, 10],
        [ 1,  1, 23],
        [ 8, 13,  5],
        [26,  4, 23]],

       [[14, 25,  9],
        [29, 19, 15],
        [23,  8, 15],
        [11, 12,  2],
        [29, 23, 28]]])

- El segundo de 3 matrices, 2 filas y 5 columnas

In [16]:
array_3d2 = np.random.randint(1,30, (3,2,5))
array_3d2

array([[[21, 17, 20, 24, 21],
        [16, 10, 21, 14, 27]],

       [[19,  7,  6, 13, 22],
        [14, 22, 14,  4, 19]],

       [[23,  6, 14, 17, 11],
        [29, 16,  4, 13,  7]]])

- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [10]:
def propiedades(array):
    print(f'forma: {array.shape}')
    print(f'tamaño: {array.size}')
    print(f'número de dimensiones: {array.ndim}')
    print(f'typo de dato: {array.dtype}')

In [11]:
propiedades(array_3d1)

forma: (2, 5, 3)
tamaño: 30
número de dimensiones: 3
typo de dato: int64


In [12]:
propiedades(array_3d2)

forma: (3, 2, 5)
tamaño: 30
número de dimensiones: 3
typo de dato: int64


- Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [13]:
np.add(array_3d1, array_3d2)

# no se puede porque tienen distintas formas

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
    - reshape()
    - transpose()

    Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [17]:
array_3d2_nuevo = np.reshape(array_3d2, (2,5,3))
array_3d2_nuevo

array([[[21, 17, 20],
        [24, 21, 16],
        [10, 21, 14],
        [27, 19,  7],
        [ 6, 13, 22]],

       [[14, 22, 14],
        [ 4, 19, 23],
        [ 6, 14, 17],
        [11, 29, 16],
        [ 4, 13,  7]]])

In [18]:
array_3d2_nuevo2 = np.transpose(array_3d2, (1,2,0))
array_3d2_nuevo2

array([[[21, 19, 23],
        [17,  7,  6],
        [20,  6, 14],
        [24, 13, 17],
        [21, 22, 11]],

       [[16, 14, 29],
        [10, 22, 16],
        [21, 14,  4],
        [14,  4, 13],
        [27, 19,  7]]])

In [20]:
np.add(array_3d2_nuevo, array_3d2_nuevo2)

# ahora sí que podemos sumar porque tienen la misma forma

array([[[42, 36, 43],
        [41, 28, 22],
        [30, 27, 28],
        [51, 32, 24],
        [27, 35, 33]],

       [[30, 36, 43],
        [14, 41, 39],
        [27, 28, 21],
        [25, 33, 29],
        [31, 32, 14]]])

In [21]:
np.subtract(array_3d2_nuevo, array_3d2_nuevo2)

array([[[  0,  -2,  -3],
        [  7,  14,  10],
        [-10,  15,   0],
        [  3,   6, -10],
        [-15,  -9,  11]],

       [[ -2,   8, -15],
        [ -6,  -3,   7],
        [-15,   0,  13],
        [ -3,  25,   3],
        [-23,  -6,   0]]])

In [22]:
np.multiply(array_3d2_nuevo, array_3d2_nuevo2)

array([[[441, 323, 460],
        [408, 147,  96],
        [200, 126, 196],
        [648, 247, 119],
        [126, 286, 242]],

       [[224, 308, 406],
        [ 40, 418, 368],
        [126, 196,  68],
        [154, 116, 208],
        [108, 247,  49]]])

In [23]:
np.divide(array_3d2_nuevo, array_3d2_nuevo2)

array([[[1.        , 0.89473684, 0.86956522],
        [1.41176471, 3.        , 2.66666667],
        [0.5       , 3.5       , 1.        ],
        [1.125     , 1.46153846, 0.41176471],
        [0.28571429, 0.59090909, 2.        ]],

       [[0.875     , 1.57142857, 0.48275862],
        [0.4       , 0.86363636, 1.4375    ],
        [0.28571429, 1.        , 4.25      ],
        [0.78571429, 7.25      , 1.23076923],
        [0.14814815, 0.68421053, 1.        ]]])