# Pair Programming NumPy I

In [2]:
import numpy as np

Empezamos nuevo bloque de ejercicios de pair programming de NumPy.
En el ejercicio de hoy vamos a empezar a trabajar con NumPy. El objetivo de estos ejericicios es que creeis una serie de arrays, y hagáis una serie de operaciones matemáticas con ellos.  
1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.  
    📌 Nota
    - El array de 2 dimensiones debe ser de 2 filas y 3 columnas
    - El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [3]:
array1d = np.random.randint(0, 10, 5)
array1d

array([8, 7, 5, 1, 6])

In [4]:
array2d = np.random.randint(0, 10, (2, 3))
array2d

array([[4, 2, 6],
       [4, 7, 3]])

In [5]:
array3d = np.random.randint(0, 10, (2, 3, 5))
array3d

array([[[3, 5, 6, 9, 4],
        [9, 0, 7, 1, 8],
        [3, 6, 3, 5, 1]],

       [[1, 8, 5, 7, 4],
        [9, 6, 7, 4, 5],
        [2, 1, 9, 8, 8]]])

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [6]:
def propiedades(array):
    print(f'forma: {array.shape}')
    print(f'tamaño: {array.size}')
    print(f'número de dimensiones: {array.ndim}')
    print(f'typo de dato: {array.dtype}')


In [8]:
propiedades(array1d)

forma: (5,)
tamaño: 5
número de dimensiones: 1
typo de dato: int64


In [9]:
propiedades(array2d)

forma: (2, 3)
tamaño: 6
número de dimensiones: 2
typo de dato: int64


In [10]:
propiedades(array3d)

forma: (2, 3, 5)
tamaño: 30
número de dimensiones: 3
typo de dato: int64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [11]:
matriz_id = np.identity(3)
matriz_id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [12]:
array_ones_l = np.ones_like(array3d)
array_ones_l

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5. Es el momento de hacer algunas operaciones entre arrays  
    - ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

In [13]:
array2d

array([[4, 2, 6],
       [4, 7, 3]])

In [14]:
matriz_id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
suma = np.add(array2d, matriz_id) # No se pueden sumar porque no tienen la misma forma

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

- En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [16]:
matriz2 = np.random.randint(10, 20, (3, 3))
matriz2

array([[13, 15, 17],
       [16, 18, 17],
       [11, 18, 14]])

In [17]:
suma2 = np.add(matriz2, matriz_id)
suma2

array([[14., 15., 17.],
       [16., 19., 17.],
       [11., 18., 15.]])

- Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [18]:
multiplicacion = np.multiply(matriz2, matriz_id)
multiplicacion

array([[13.,  0.,  0.],
       [ 0., 18.,  0.],
       [ 0.,  0., 14.]])

- Dividid las dos matricess

In [19]:
division = np.divide(matriz2, matriz_id)
division

/tmp/ipykernel_1546/3874293228.py:1: RuntimeWarning: divide by zero encountered in divide
  division = np.divide(matriz2, matriz_id)


array([[13., inf, inf],
       [inf, 18., inf],
       [inf, inf, 14.]])